[package]
name = "spin-sdk"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = "1.64"

[lib]
name = "spin_sdk"

[dependencies]
anyhow = "1"
bytes = "1"
form_urlencoded = "1.0"
http_types = { package = "http", version = "0.2" }
spin-macro = { path = "macro" }
thiserror = "1.0.37"
wit-bindgen = "0.6"
routefinder = "0.5.3"

[features]
default = [ "export-sdk-language" ]
export-sdk-language = []
